<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class RecipesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $recipes = [
            [
                'user_id' => 1,
                'title' => 'Spaghetti Carbonara',
                'ingredients' => 'Spaghetti, Eggs, Parmesan cheese, Pancetta, Black pepper',
                'steps' => 'Cook the spaghetti according to the package instructions. In a bowl, whisk together the eggs and Parmesan cheese. Fry the pancetta in a pan until it is crisp. Combine the hot spaghetti with the pancetta and mix in the egg mixture. Serve with additional Parmesan cheese and a sprinkle of black pepper.',
                'category_id' => 2,
                'cooking_time' => '20 minutes',
                'calories' => 500,
                'fat' => 20,
                'protein' => 25,
                'carbs' => 50,
                'img_url' => 'https://example.com/spaghetti_carbonara.jpg',
                'no_of_likes' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'title' => 'Caesar Salad',
                'ingredients' => 'Romaine lettuce, Croutons, Caesar dressing, Parmesan cheese, Chicken breast',
                'steps' => 'Grill the chicken breast and slice it into strips. Toss the romaine lettuce with Caesar dressing until evenly coated. Add the croutons and Parmesan cheese, then top with the grilled chicken slices. Serve immediately.',
                'category_id' => 4,
                'cooking_time' => '15 minutes',
                'calories' => 300,
                'fat' => 15,
                'protein' => 25,
                'carbs' => 20,
                'img_url' => 'https://example.com/caesar_salad.jpg',
                'no_of_likes' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'title' => 'Chocolate Cake',
                'ingredients' => 'Flour, Cocoa powder, Sugar, Eggs, Butter, Baking powder, Milk',
                'steps' => 'Preheat the oven to 350°F (175°C). In a bowl, mix together the flour, cocoa powder, sugar, and baking powder. Add the eggs, melted butter, and milk, and mix until the batter is smooth. Pour the batter into a greased baking pan and bake for 30-35 minutes. Let the cake cool before serving.',
                'category_id' => 3,
                'cooking_time' => '45 minutes',
                'calories' => 400,
                'fat' => 18,
                'protein' => 6,
                'carbs' => 58,
                'img_url' => 'https://example.com/chocolate_cake.jpg',
                'no_of_likes' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'title' => 'Tomato Soup',
                'ingredients' => 'Tomatoes, Onion, Garlic, Vegetable broth, Olive oil, Basil, Salt, Pepper',
                'steps' => 'Sauté the chopped onion and garlic in olive oil until softened. Add the chopped tomatoes and cook until they are soft. Pour in the vegetable broth and bring the mixture to a boil. Simmer for 20 minutes. Blend the soup until smooth, then season with salt, pepper, and fresh basil.',
                'category_id' => 5,
                'cooking_time' => '30 minutes',
                'calories' => 150,
                'fat' => 7,
                'protein' => 3,
                'carbs' => 20,
                'img_url' => 'https://example.com/tomato_soup.jpg',
                'no_of_likes' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'title' => 'Mango Smoothie',
                'ingredients' => 'Mango, Banana, Yogurt, Honey, Ice cubes',
                'steps' => 'Peel and chop the mango and banana, then add them to a blender with the yogurt, honey, and ice cubes. Blend until the mixture is smooth. Pour the smoothie into glasses and serve immediately.',
                'category_id' => 6,
                'cooking_time' => '5 minutes',
                'calories' => 200,
                'fat' => 2,
                'protein' => 5,
                'carbs' => 45,
                'img_url' => 'https://example.com/mango_smoothie.jpg',
                'no_of_likes' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'title' => 'French Toast',
                'ingredients' => 'Bread, Eggs, Milk, Cinnamon, Sugar, Butter, Maple syrup',
                'steps' => 'In a bowl, whisk together the eggs, milk, cinnamon, and sugar. Dip the bread slices in the egg mixture until they are well-coated. Fry the bread in a pan with butter until each side is golden brown. Serve with maple syrup.',
                'category_id' => 7,
                'cooking_time' => '15 minutes',
                'calories' => 350,
                'fat' => 15,
                'protein' => 10,
                'carbs' => 45,
                'img_url' => 'https://example.com/french_toast.jpg',
                'no_of_likes' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'title' => 'Garlic Bread',
                'ingredients' => 'Baguette, Butter, Garlic, Parsley, Parmesan cheese',
                'steps' => 'Preheat the oven to 375°F (190°C). Mix softened butter with minced garlic and chopped parsley. Spread the mixture on slices of baguette and sprinkle with Parmesan cheese. Bake for 10-15 minutes. Serve warm.',
                'category_id' => 8,
                'cooking_time' => '20 minutes',
                'calories' => 250,
                'fat' => 12,
                'protein' => 7,
                'carbs' => 28,
                'img_url' => 'https://example.com/garlic_bread.jpg',
                'no_of_likes' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'title' => 'Guacamole',
                'ingredients' => 'Avocados, Lime, Onion, Tomato, Cilantro, Salt, Pepper',
                'steps' => 'Mash the avocados in a bowl. Add lime juice, finely chopped onion, diced tomato, and chopped cilantro. Mix well and season with salt and pepper. Serve with tortilla chips.',
                'category_id' => 1,
                'cooking_time' => '10 minutes',
                'calories' => 150,
                'fat' => 10,
                'protein' => 2,
                'carbs' => 15,
                'img_url' => 'https://example.com/guacamole.jpg',
                'no_of_likes' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'title' => 'Oatmeal Cookies',
                'ingredients' => 'Oats, Flour, Sugar, Brown sugar, Butter, Eggs, Vanilla, Baking soda, Cinnamon, Raisins',
                'steps' => 'Preheat the oven to 350°F (175°C). Cream together the butter, sugar, and brown sugar. Beat in the eggs and vanilla. Mix in the flour, baking soda, and cinnamon. Stir in the oats and raisins. Drop by spoonfuls onto a baking sheet and bake for 10-12 minutes.',
                'category_id' => 3,
                'cooking_time' => '25 minutes',
                'calories' => 120,
                'fat' => 5,
                'protein' => 2,
                'carbs' => 18,
                'img_url' => 'https://example.com/oatmeal_cookies.jpg',
                'no_of_likes' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 9,
                'title' => 'Chicken Curry',
                'ingredients' => 'Chicken, Onion, Garlic, Ginger, Tomatoes, Curry powder, Coconut milk, Cilantro',
                'steps' => 'Sauté the chopped onion, garlic, and ginger in oil until softened. Add the chicken pieces and cook until they are browned. Stir in the curry powder and chopped tomatoes, then add the coconut milk. Simmer the mixture until the chicken is cooked through. Garnish with fresh cilantro and serve with rice.',
                'category_id' => 2,
                'cooking_time' => '40 minutes',
                'calories' => 600,
                'fat' => 30,
                'protein' => 35,
                'carbs' => 50,
                'img_url' => 'https://example.com/chicken_curry.jpg',
                'no_of_likes' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('recipes')->insert($recipes);
    }
}
